name: Build OpenCentauri FW

on:
  workflow_call:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Download firmware
        run: |
          ./fwdl.sh

      - name: Patch firmware
        run: |
          ./build.sh
      
      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: update/update.swu