name: Build OpenCentauri FW

on:
  workflow_call:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  FW_VER: 1.1.40

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt install -y bsdiff
      
      - name: Download firmware
        run: |
          ./fwdl.sh $FW_VER

      - name: Patch and build firmware
        run: |
          ./build.sh $FW_VER
      
      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: update/update.swu
